### ISSUE TITLE
FT on COCO in Different Language

### ISSUE THREAD

**Issue by krbuettner** [ghchen18/acl23_mclip#1]
Excellent repo! I was wondering if there are instructions to FT on COCO captions in a different language than English (e.g. Japanese)? I could be wrong but the preprocess.sh looks like for English-only

**Comment by ghchen18** [comment]
You can follow the preprocess code for multi30k [here](https://github.com/ghchen18/acl23_mclip/blob/main/scripts/preprocess.sh#L83).
